### ISSUE TITLE
Could not locate box "templates" on 1.46.0

### ISSUE THREAD

**Issue by ahmedre** [bitrise-io/bitrise#765] opened 2021-05-26 13:57 UTC
Hi,
I am seeing issue #667 come up again on version 1.46.0 (though if I downgrade to 1.44.0, everything works fine). Installed via homebrew and then ran `bitrise setup`, and then tried to make a step by running `bitrise :step create`. 

<img width="682" alt="Screen Shot 2021-05-26 at 5 56 57 PM" src="https://user-images.githubusercontent.com/47771/119672577-c57c1480-be4b-11eb-8318-8127d8286c29.png">

**Comment by BirmacherAkos** [comment] 2021-06-09 08:07
Thanks @ahmedre, we'll check the issue.

**Comment by mateherber** [comment] 2021-06-10 11:38
Duplicate of https://github.com/bitrise-io/bitrise-plugins-step/issues/27

**Comment by mateherber** [comment] 2021-06-14 07:35
Hi @ahmedre!

Please use the newest `0.10.1` version of the `step` bitrise plugin (update via `bitrise plugin update step`) to avoid this issue.
I'm closing this issue now. Should you experience any other problems, please open a new issue for the plugin!

**Closed by mateherber** 2021-06-14 07:35 UTC
Labels: bug
