### ISSUE TITLE
Steplib update fails if not supported key (e. g. category) found

### ISSUE THREAD

**Issue by erosdome** [bitrise-io/bitrise#509] opened 2017-06-08 14:02 UTC
From a build's logs:

```
Failed to walk through path:Not supported key found in options: "category" 
Failed to update StepLib (https://github.com/bitrise-io/bitrise-steplib.git), error: Not supported key found in options: "category"
```

**Comment by viktorbenei** [comment] 2017-06-08 16:33
When updating the steplib and generating the JSON for it we could simply skip the "options" (`opts`) which are new / not handled in the current version of the CLI / stepman.

That way if for some reason you want to keep using an older CLI you still could.

**Comment by vgaidarji** [comment] 2017-08-17 09:37
Here're the steps to fix the issue on Mac OS, (as per discussion with @viktorbenei):
-  `brew uninstall bitrise`
- `which bitrise`. If there's a bitrise binary, we need to remove it as well. 
(e.g.: `rm /usr/local/bin/bitrise`)
- `brew install bitrise` 
- `bitrise setup --clean` for full clean setup

Complete reinstall of bitrise CLI fixed the issue for me.

**Comment by viktorbenei** [comment] 2017-08-17 09:38
Thanks for sharing @vgaidarji ! ;)

**Comment by elashpear** [comment] 2019-02-14 19:26
@viktorbenei We have also encountered this issue when upgrading bitrise CLI from `1.26.0 -> 1.27.0` with workflow-editor `1.1.48`. Before the CLI upgrade everything worked fine. After the upgrade we get errors like so when running workflow editor:

```
Searching for bitrise.yml at: /Users/eliot/Dev/pear/poe/bitrise.yml
Starting API server at http://localhost:52286
Workflow editor URL: http://localhost:52286/1.1.48/
 => POST: /api/connection - 4.142µs ()
 => GET: /api/bitrise-yml.json - 31.006953ms ()
not supported key found in options: unset
not supported key found in options: unset
not supported key found in options: unset
 => POST: /api/step-info - 2.169496231s (application/json;charset=UTF-8)
 => POST: /api/step-info - 2.169139169s (application/json;charset=UTF-8)
 => POST: /api/step-info - 2.167295456s (application/json;charset=UTF-8)
not supported key found in options: unset
 => POST: /api/step-info - 2.246229027s (application/json;charset=UTF-8)
not supported key found in options: unset
 => POST: /api/step-info - 2.287641099s (application/json;charset=UTF-8)
not supported key found in options: unset
 => POST: /api/step-info - 2.324590086s (application/json;charset=UTF-8)
 => POST: /api/spec - 469.851941ms (application/json;charset=UTF-8)
```
Reinstalling CLI has not fixed the issue.

**Comment by viktorbenei** [comment] 2019-02-15 11:18
Managed to reproduce the issue reported by @elashpear - yml: https://github.com/viktorbenei/devops-exercises/blob/master/simple-code/echo-server/bitrise.yml

**Comment by trapacska** [comment] 2019-02-15 13:56
Hey @elashpear !

Thank you for the report! We've found the root cause and we already fixed it. To solve the error you recently encountered is now just simply call a `bitrise update` and a `bitrise setup` command.

Please let us know if you still encounter any issues with it.
Closing this issue ticket now but feel free to re-open if you still encounter issues with it.

**Comment by viktorbenei** [comment] 2019-02-15 16:51
@trapacska I re-opened this issue for the original content, that the CLI should not fail if there's an unknown/unsupported (new!) key, as that means that older CLI versions stop working suddenly when this happens.

**Comment by nespejau** [comment] 2019-03-17 00:12
Shortly thank you for suport and friendly and helpful piece :-)

**Comment by nespejau** [comment] 2019-03-17 00:15
Stay tuned and you will get data about my projects 😊🤸⛹️🏋️

**Comment by richard-bogdan-bitrise** [comment] 2019-07-03 12:13
Closing issue, as fix is provided. If anything related to this arises, please raise a new ticket.

**Closed by richard-bogdan-bitrise** 2019-07-03 12:13 UTC
Labels: bug, enhancement, ready
