### ISSUE TITLE
Option to (temporarily) disable steps

### ISSUE THREAD

**Issue by deanWombourne** [bitrise-io/bitrise#560] opened 2017-12-10 20:21 UTC
Hi,

It would be useful (definitely to me, maybe to others) to be able to disable steps in a workflow without deleting them and then re-adding them later.

Use case:

I'm debugging an issue in the workflow (not reproducible locally, annoyingly) but don't want to upload every result to Slack while I'm debugging. Also don't want to upload to our binary repository etc.

Potential solution:

A tick box (similar to the 'run if previous step failed') which disables this step. Subsequent steps would treat this as a success (though, obviously, any outputs wouldn't be filled out!). 

This could be represented in the yml as a single bool (`disabled: true`) - it's absence would imply `disabled: false` which would give backwards compatibility / remove spurious noise from the bitrise.yml.

The disabled steps could be clearly marked as disabled in the workflow editor (greyed out etc - lots of choices here)

The step output from the cli would show which steps were skipped, something like:

```
+------------------------------------------------------------------------------+
| (2) Output to Slack                                                          |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-12-10T11:44:02-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
WARN[20:18:40] This step is disabled - skipping.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| - | Output to Slack                                               | 0.40 sec |
+---+---------------------------------------------------------------+----------+
```

S

**Comment by koral--** [comment] 2017-12-10 22:16
Such feature is already supported by CLI: https://devcenter.bitrise.io/tips-and-tricks/disable-a-step-by-condition/#disable-a-step
As far as I can see it is not (yet) supported by graphical workflow editor. Here is a related feature request: https://discuss.bitrise.io/t/allow-disabling-a-step-in-the-workflow/711

**Comment by viktorbenei** [comment] 2017-12-11 09:04
@koral-- 's right, thanks @deanWombourne for the infos / feature request, but I'll have to close this here as a duplicate of https://discuss.bitrise.io/t/allow-disabling-a-step-in-the-workflow/711

Please vote & comment there, at https://discuss.bitrise.io/t/allow-disabling-a-step-in-the-workflow/711 to keep the feature request at a single location & to make it easier for others to find it and vote on it, bumping its priority ;)

Of course if you have any questions just let us know!

**Closed by viktorbenei** 2017-12-11 09:04 UTC
Labels: feature-request, question
